# Generated by Django 3.1.2 on 2020-10-01 20:41

import garnett.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pages', models.PositiveIntegerField()),
                ('title', garnett.fields.TranslatedCharField()),
                ('description', garnett.fields.TranslatedTextField()),
            ],
        ),
    ]
