# Generated by Django 3.1.4 on 2021-02-03 23:45

from django.db import migrations, models
import garnett.fields
import library_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_pages", models.PositiveIntegerField()),
                (
                    "title",
                    garnett.fields.TranslatedCharField(
                        fallback=library_app.models.title_fallback,
                        field=models.CharField(
                            max_length=250,
                            validators=[library_app.models.validate_length],
                        ),
                    ),
                ),
                ("author", models.TextField()),
                (
                    "description",
                    garnett.fields.TranslatedTextField(
                        fallback=garnett.fields.translation_fallback,
                        field=models.TextField(),
                    ),
                ),
                ("category", models.JSONField()),
            ],
        ),
    ]
