# Generated by Django 3.1.2 on 2020-12-22 00:16

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension
import garnett.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_pages", models.PositiveIntegerField()),
                ("title", garnett.fields.TranslatedCharField()),
                ("author", models.TextField()),
                ("description", garnett.fields.TranslatedTextField()),
                ("category", models.JSONField()),
            ],
        ),
    ]
