# Generated by Django 3.1.13 on 2022-01-11 10:13

from django.db import migrations, models
import garnett.fields
import library_app.models
from garnett.migrate import step_1_safe_encode_content, step_2_safe_prepare_translations


model_fields = {
    "book": ["title", "description"],
}


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        step_1_safe_encode_content("library_app", model_fields),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=garnett.fields.TranslatedField(
                models.TextField(
                    help_text="Short details about a book. (Multilingal field)"
                ),
                fallback=None,
                help_text="Short details about a book. (Multilingal field)",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=garnett.fields.TranslatedField(
                models.CharField(
                    max_length=250, validators=[library_app.models.validate_length]
                ),
                fallback=library_app.models.TitleTranslatedStr,
                help_text="The name for a book. (Multilingal field)",
            ),
        ),
        step_2_safe_prepare_translations("library_app", model_fields),
    ]
