# Generated by Django 3.1.4 on 2021-02-10 22:51

from django.db import migrations, models
import functools
import garnett.fields
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0002_enable_trigram"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultBook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_pages", models.PositiveIntegerField()),
                (
                    "title",
                    garnett.fields.TranslatedField(
                        models.CharField(blank=True, default="DEFAULT TITLE"),
                        default=functools.partial(
                            garnett.fields.translatable_default,
                            *("DEFAULT TITLE",),
                            **{}
                        ),
                        fallback=garnett.fields.translation_fallback,
                    ),
                ),
                (
                    "author",
                    garnett.fields.TranslatedField(
                        models.CharField(
                            blank=True, default=library_app.models.default_author
                        ),
                        default=functools.partial(
                            garnett.fields.translatable_default,
                            *(library_app.models.default_author,),
                            **{}
                        ),
                        fallback=garnett.fields.translation_fallback,
                    ),
                ),
            ],
        ),
    ]
