# Generated by Django 3.2.12 on 2022-03-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_make_translatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.CharField(default='', help_text='Notes about the book (single language field', max_length=512),
        ),
    ]
