# Generated by Django 3.1.6 on 2021-07-03 12:41

from django.db import migrations, models
import garnett.fields
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0003_defaultbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureBook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    garnett.fields.TranslatedField(
                        library_app.models.InverseTextField(), fallback=None
                    ),
                ),
                ("author", library_app.models.InverseTextField()),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=garnett.fields.TranslatedField(
                models.TextField(
                    help_text="Short details about a book. (Multilingual field)"
                ),
                fallback=None,
                help_text="Short details about a book. (Multilingual field)",
            ),
        ),
    ]
