name: Testing
on: [push, pull_request]

jobs:
  test:
    needs:
      - python_lint
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox -e dj-31-db-sqlite
