name: Testing
on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tox
        run: pip install tox

      - name: Where am I?
        run: echo "-- . --" && ls . && echo "--test--" && ls ./test && echo "--test/tests--" && ls ./test/tests && echo "--test/library_app--" && ls ./test/library_app
        
      - name: Run tests
        run: tox -e dj-31-db-sqlite
