name: Testing
on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: changeme
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mariadb:
        # Docker Hub image
        image: mariadb:10
        env:
          # MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        # Set health checks to wait until postgres has started
        ports:
          - 113306:3306
        options: >-
          --health-cmd "/usr/bin/mysql --user=root --execute \"SHOW DATABASES;\""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tox
        run: pip install tox
        
      # - name: Run SQLite tests
      #   run: tox -e dj-31-db-sqlite
        
      # - name: Run Postgres tests
      #   env:
      #     DATABASE_URL: postgres://postgres:changeme@localhost:5432/test
      #   run: tox -e dj-31-db-pg
        
      - name: Run MariaDB tests
        env:
          DATABASE_URL: mysql://root:@localhost:3306/test
        run: /usr/bin/mysql --host localhost --port 113306 --user=root --execute \"SHOW DATABASES;\"
        # run: tox -e dj-31-db-maria

      - name: Coverage report
        run: coverage report -m
